workflow Building blocks added

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,1 +1,21 @@
-
+name: 01 - Building Blocks
+on:
+  - push
+  - workflow_dispatch
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps: 
+      - name: Say Hello
+        run: echo "Hello, world!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will Fail" 
+          exit 1
+      - name: Say goodbye
+        run: echo "goodbye!"
+        
+      
